### ISSUE TITLE
Font.

### ISSUE THREAD

**Issue by Giovanni2230** [zachoooo/Broadcast#6]
Hello, how i can put &l (Bold letters) on broadcast? and ty .

**Comment by zachoooo** [comment]
The messaging format is done in JSON. The easiest way to generate it is with a helper like this: https://minecraft.tools/en/tellraw.php

Heres a really simple example:

```hocon
delay=60
messages=[
    {
        "text":"I'm a bold message!",
        "bold":true
    }
]
prefix {
    extra=[
        {
            color=yellow
            text=Broadcast
        },
        {
            text="] "
        }
    ]
    text="["
}
random=false
no-repeat=true
```
